prompt_read_time_minutes:
  default: 2
  type: integer
prompt_topics:
  default: 2
  type: integer
prompt_hide_duration_minutes:
  default: 1440
  type: integer
console_decision_logging:
  default: false
  type: bool